/**
 * @fileoverview gRPC-Web generated client stub for org.price.stream
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v6.31.1
// source: StockFeed.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.org = {};
proto.org.price = {};
proto.org.price.stream = require('./StockFeed_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.org.price.stream.StockFeedClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.org.price.stream.StockFeedPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.org.price.stream.Empty,
 *   !proto.org.price.stream.PriceUpdate>}
 */
const methodDescriptor_StockFeed_StreamPrices = new grpc.web.MethodDescriptor(
  '/org.price.stream.StockFeed/StreamPrices',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.org.price.stream.Empty,
  proto.org.price.stream.PriceUpdate,
  /**
   * @param {!proto.org.price.stream.Empty} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.org.price.stream.PriceUpdate.deserializeBinary
);


/**
 * @param {!proto.org.price.stream.Empty} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.org.price.stream.PriceUpdate>}
 *     The XHR Node Readable Stream
 */
proto.org.price.stream.StockFeedClient.prototype.streamPrices =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/org.price.stream.StockFeed/StreamPrices',
      request,
      metadata || {},
      methodDescriptor_StockFeed_StreamPrices);
};


/**
 * @param {!proto.org.price.stream.Empty} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.org.price.stream.PriceUpdate>}
 *     The XHR Node Readable Stream
 */
proto.org.price.stream.StockFeedPromiseClient.prototype.streamPrices =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/org.price.stream.StockFeed/StreamPrices',
      request,
      metadata || {},
      methodDescriptor_StockFeed_StreamPrices);
};


module.exports = proto.org.price.stream;

